### ISSUE TITLE
Exit w/o error when tag already exists

### ISSUE THREAD

**Issue by agarzola** [pkgdeps/git-tag-action#2]
Hi. Thank you for creating this action. It is quite handy!

I’ve found that when a tag already exists (which will often be the case in my project), this action exits with an error:
>Error: Reference already exists

In these cases, the job appears as failed:
![screenshot of failed job](https://p191.p3.n0.cdn.getcloudapp.com/items/bLug6Ro4/3c6d1535-55f1-4a8c-a8fc-a14babbc6fbb.png?v=3310b72ff58eb10d00d0e88b0643e65d)

I would like for the job to exit with a success status even when the tag already exists. Would you be interested in providing an option not to exit with an error in such cases? I would be happy to submit a pull request if so.

Thanks again!

**Comment by azu** [comment]
Fmm, It is an unexpected error.

if the repository already has the ref(tag ref), this action does not push a new tag.
https://github.com/pkgdeps/git-tag-action/blob/f34f3f8ad2222581bced96bb41618c3c501ee199/src/tag.ts#L20-L26

Can you get debug log of the action and paste it?

- https://github.com/actions/toolkit/blob/master/docs/action-debugging.md#step-debug-logs
  - `core.debug` shown log when action is debug mode.

**Comment by agarzola** [comment]
@azu Sure! I set `ACTIONS_STEP_DEBUG` to `true` and re-ran the workflow on a feature branch. [Here’s the resulting log.](https://github.com/ChromaticHQ/maui-jim-styleguide/commit/8f1f4ced903932d487c4d1bc11d688d826886fd2/checks/1778165230/logs)

**Comment by azu** [comment]
@agarzola Thanks, but I can not see the link.
It seems that GitHub Action's log is private only.
Can you paste it to https://gist.github.com/ and share it? ( ⚠️ please be careful not to include secrets info)

**Comment by agarzola** [comment]
Oh, weird. I’m able to load it from a private (i.e. anonymous) window. 🤔 In any case, I’ve pasted the contents of the log into [this gist](https://gist.github.com/agarzola/176bfb1ace12e7a743133646bd4da8ad). I had checked before sharing the previous link: it appears that secrets are redacted from the log by default. Thanks for the reminder, though! 😄

**Comment by azu** [comment]
Probably, I fixed it.
https://github.com/pkgdeps/git-tag-action/releases/tag/v2.0.2
