### ISSUE TITLE
Node 12 has been deprecated by GitHub

### ISSUE THREAD

**Issue by nikkag** [pkgdeps/git-tag-action#9]
The request is to update the Node version used to 16.

More information here: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by azu** [comment]
Thanks.

We need to update it
https://github.com/pkgdeps/git-tag-action/blob/9aaf6c4b9adac3084f17e3a16cc8d7f7e86d98ed/action.yml#L22

**Comment by azu** [comment]
fixed in https://github.com/pkgdeps/git-tag-action/releases/tag/v2.0.6
